import { ArrowRight, BadgeCheck, Clock3, PlaneTakeoff, ShieldCheck } from "lucide-react";
import { SectionCard, StatusPill, ProgressBar, formatCurrency, formatRoute, asList, classNames } from "./TravelUI.jsx";

function FlightCard({ flight, index }) {
  const recommended = flight?.recommended || index === 0;
  const bestValue = flight?.bestValue || index === 1;
  const badges = [
    recommended ? "Recommended" : null,
    bestValue ? "Best Value" : null,
    flight?.source ? String(flight.source).replace(/_/g, " ") : null
  ].filter(Boolean);

  return (
    <article className="group rounded-[26px] border border-white/10 bg-gradient-to-br from-white/10 to-white/5 p-4 transition duration-300 hover:-translate-y-1 hover:border-cyan-300/20 hover:bg-white/10">
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-cyan-400/20 to-indigo-400/20 text-cyan-100 ring-1 ring-white/10">
            <PlaneTakeoff size={20} />
          </div>
          <div>
            <p className="text-sm font-semibold text-white">{flight.airline || "Recommended carrier"}</p>
            <p className="text-xs text-white/50">{flight.flightNumber || "Flight number on request"}</p>
          </div>
        </div>
        <StatusPill tone={recommended ? "success" : "neutral"}>{recommended ? "Top pick" : "Alternative"}</StatusPill>
      </div>

      <div className="mt-4 flex items-center justify-between gap-4">
        <div className="min-w-0 flex-1">
          <p className="text-sm font-medium text-white/75">{formatRoute(flight.route, flight.origin, flight.destination)}</p>
          <div className="mt-3 flex items-center gap-3 text-xs text-white/[0.55]">
            <span>{flight.departure || "Departure on request"}</span>
            <ArrowRight size={12} />
            <span>{flight.arrival || flight.return || "Return on request"}</span>
          </div>
        </div>

        <div className="text-right">
          <p className="text-xs uppercase tracking-[0.18em] text-white/[0.45]">Price</p>
          <p className="mt-1 text-2xl font-semibold tracking-tight text-cyan-100">
            {formatCurrency(flight.estimatedPrice, flight.price || "Check live fares")}
          </p>
        </div>
      </div>

      <div className="mt-4">
        <ProgressBar value={recommended ? 88 : bestValue ? 80 : 72} />
      </div>

      <div className="mt-4 flex flex-wrap gap-2">
        {badges.map((badge) => (
          <span
            key={badge}
            className="inline-flex items-center gap-1 rounded-full border border-white/10 bg-white/5 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-white/[0.65]"
          >
            <BadgeCheck size={11} className="text-cyan-300" />
            {badge}
          </span>
        ))}
      </div>

      <div className="mt-4 flex items-start gap-3 rounded-2xl border border-white/10 bg-slate-950/30 p-3 text-sm text-white/[0.72]">
        <ShieldCheck size={16} className="mt-0.5 shrink-0 text-emerald-300" />
        <p>{flight.recommendation || "This option balances duration, price, and convenience."}</p>
      </div>

      <div className="mt-4 flex items-center gap-2 text-xs text-white/50">
        <Clock3 size={12} />
        <span>{flight.duration || flight.durationText || "Duration available in the final plan"}</span>
      </div>
    </article>
  );
}

export default function FlightCards({ flights }) {
  const options = flights?.options || [];
  if (!options.length) return null;

  return (
    <SectionCard
      eyebrow="Available flights"
      title="Flights"
      description={flights?.flightSummary || "Curated options generated by the flight agent."}
      icon={PlaneTakeoff}
      action={<StatusPill tone="active">{options.length} options</StatusPill>}
    >
      <div className="grid gap-4 xl:grid-cols-2">
        {options.slice(0, 4).map((flight, index) => (
          <FlightCard key={`${flight.flightNumber || flight.airline || "flight"}-${index}`} flight={flight} index={index} />
        ))}
      </div>
      {flights?.estimatedTotal ? (
        <div className="mt-4 flex items-center justify-between rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white/75">
          <span className="font-medium">Estimated total</span>
          <span className="font-semibold text-cyan-100">{formatCurrency(flights.estimatedTotal, flights.estimatedTotal)}</span>
        </div>
      ) : null}
    </SectionCard>
  );
}
