import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Link2, Trash2 } from "lucide-react";
import { api } from "../services/api.js";
import LoadingSkeleton from "../components/LoadingSkeleton.jsx";

export default function DashboardPage() {
  const [trips, setTrips] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  async function loadTrips() {
    setLoading(true);
    try {
      const { data } = await api.get("/trips");
      setTrips(data.trips);
    } catch (err) {
      setError(err.response?.data?.message || "Could not load trips");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadTrips();
  }, []);

  async function removeTrip(id) {
    await api.delete(`/trips/${id}`);
    setTrips((items) => items.filter((trip) => trip._id !== id));
  }

  async function shareTrip(id) {
    const { data } = await api.post(`/trips/${id}/share`);
    await navigator.clipboard.writeText(`${window.location.origin}${data.shareUrl}`);
  }

  return (
    <section>
      <h1 className="text-2xl font-black">Saved Trips</h1>
      <p className="mt-2 text-sm text-slate-600">Plans generated by the agent workflow are stored here.</p>
      {loading ? <div className="mt-6"><LoadingSkeleton /></div> : null}
      {error && <p className="mt-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}
      <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {trips.map((trip) => (
          <article key={trip._id} className="rounded border border-slate-200 bg-white p-5 shadow-sm">
            <div className="flex items-start justify-between gap-3">
              <div>
                <h2 className="font-black">{trip.destination}</h2>
                <p className="text-sm text-slate-600">{trip.budget || "Flexible budget"}</p>
              </div>
              <div className="flex gap-2">
                <button title="Share" onClick={() => shareTrip(trip._id)} className="grid h-9 w-9 place-items-center rounded bg-slate-100">
                  <Link2 size={16} />
                </button>
                <button title="Delete" onClick={() => removeTrip(trip._id)} className="grid h-9 w-9 place-items-center rounded bg-red-50 text-red-700">
                  <Trash2 size={16} />
                </button>
                <button onClick={() => navigate(`/app/chat/${trip._id}`, {
                  state: { tripSpec: trip.tripSpec, chatId: trip.chatId }
                })}>
                  Open Chat
                </button>
              </div>
            </div>
            <p className="mt-4 line-clamp-6 whitespace-pre-wrap text-sm leading-6 text-slate-700">{trip.finalResponse}</p>
          </article>
        ))}
      </div>
    </section>
  );
}
